### ISSUE TITLE
foreach错误

### ISSUE THREAD

**Issue by yegetables** [Innei/PaulTheme-for-typecho#11]
php7.2 作品介绍以及追番页报错
Warning: Invalid argument supplied for foreach()
curl及openssl都已开启
作品页是page_works_info.php line27
追番页是pual.php line16
这个主题非常漂亮,我真心希望可以解决bug越做越好
已赞赏,加油啊

**Comment by Innei** [comment]
emmm,这个是你数据填错了导致的。。

**Comment by yegetables** [comment]
在页面内容直接贴那个样例代码不对吗,我看主题说明填的

**Comment by Innei** [comment]
你需要自己抓数据，样例只是参考，并不可用

**Comment by yegetables** [comment]
追番填个bilibiliid就行了吧,作品和作品介绍不会填哎

**Comment by Innei** [comment]
emm,这个可能要自己摸索一下。Σ(ŎдŎ|||)ﾉﾉ
