### ISSUE TITLE
建议主页语录解析倒序

### ISSUE THREAD

**Issue by yegetables** [Innei/PaulTheme-for-typecho#12]
主页显示日记是由新即久的，但语录确是从久到新。请问可否考虑一下倒序排列，谢谢

**Comment by Innei** [comment]
可以考虑

**Comment by Innei** [comment]
在 paul.php 59行位置

`foreach ($say_bodys as $key => $saying) {
            yield $author_names[$key] => $saying;
        } `
把 $say_bodys 进行倒置。

`array_reverse($say_bodys)` 参见 <https://www.php.net/manual/zh/function.array-reverse.php>
