### ISSUE TITLE
点击超链接跳转的时候经常给http自动加s，无法成功打开新网页。

### ISSUE THREAD

**Issue by wucheng139** [Innei/PaulTheme-for-typecho#13]
就经常跳转失败。然后就是网络连接的问题。
![image](https://user-images.githubusercontent.com/45967120/80163649-62e19500-8609-11ea-80d9-c82c33c92c2b.png)
![image](https://user-images.githubusercontent.com/45967120/80163681-7bea4600-8609-11ea-9595-ec470d3365a7.png)

**Comment by Innei** [comment]
此主题开启了全站https。
