### ISSUE TITLE
关于追番页面的一些疑问与建议

### ISSUE THREAD

**Issue by Waitung** [Innei/PaulTheme-for-typecho#7]
今天突然看到这个主题，挺喜欢的就动手试试。
安装完主题试了一下，发现追番页少了前面一页。
`https://api.bilibili.com/x/space/bangumi/follow/list?type=1&pn=2&ps=' . $num  . '&vmid=' . $uid`
看了一下这个，用了pn=2，也就是前面会少了$num数量的番剧，是有什么考虑吗。

----

然后就是番剧链接打开都是提示页面不见了。
`https://bangumi.bilibili.com/anime/' . $list['media_id'] . '/`
这里的`media_id`应该改成`season_id`才对，或者改成`https://www.bilibili.com/bangumi/media/md' . $list['media_id'] . '/`

----

然后关于集数的建议。
`<p>集数： ' . $list['total_count'] . '</p>`
`total_count`没有完结的番都是-1，看起来怪怪的。个人把这里改成`<p>' . $list['new_ep']['index_show'] . '</p>`后，会显示成”即将开播“，”更新至第XX话“，”全XX话“，感觉效果比较好。

----

最后是关于番剧封面图片的建议。
由于这个api获取的是http链接，会导致追番页面显示部分内容不安全之类的提示。建议处理一下替换成https。
末尾感谢一下移植工作，挺喜欢的一个主题。

**Comment by Innei** [comment]
但是抓接口的时候，没考虑这么多。（其实但是我也不懂这个pn是啥），好吧我现在知道pn是页数了，太惭愧了。之后一直没有什么bug，我就没去考虑这么多。总之，感谢反馈。现已修复。
