### ISSUE TITLE
默认头像不显示

### ISSUE THREAD

**Issue by feitisn** [Innei/PaulTheme-for-typecho#8]
博主的网站还有我自己部署的博主的网站主题那个头像都是不显示的，我单独打开图片链接是可以正常打开的

**Comment by Innei** [comment]
我这能正常显示，具体能上传报错信息和截图吗

**Comment by feitisn** [comment]
![image](https://user-images.githubusercontent.com/17506837/71063051-e2b4aa00-21a6-11ea-9bcf-7af16bc8fdc5.png)

**Comment by Innei** [comment]
网站贴一下

**Comment by feitisn** [comment]
http://ft.ftloveyyq.top:82/

**Comment by Innei** [comment]
开启https 或者 删去 `header.php` 中的
```<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">```

**Comment by feitisn** [comment]
好的，谢谢博主大佬，我去试试！

**Comment by feitisn** [comment]
谢谢！已经没问题了！
